- src/routes/api/google-conversion/+server.ts
> Fix parsing table cell lists in Google Conversion API

- src/lib/components/BodyRenderer/item.pug
- src/lib/components/BodyRenderer/item.svelte
resolves https://github.com/holdex/holdex-venture-studio/issues/449,
resolves https://github.com/holdex/holdex-venture-studio/issues/313,
resolves https://github.com/holdex/holdex-venture-studio/issues/270
estimation: 30 min
> fix: replace twitter widget with inline links

- src/lib/utils/errorTransformer.ts
- src/routes/api/google-conversion/+server.ts
resolves https://github.com/holdex/holdex-venture-studio/issues/340
estimation: 2h
> feat: enable support for inline links inside quotes

- README.md
- package.json
- src/lib/config/index.ts
Changed environment variable location.
> feat: update README.md

- .vscode/settings.json
- src/routes/api/google-conversion/+server.ts
- vite.config.ts
Resolves #108 
ETA:
Hours took for new PR: 1 hr.
Hours taken until now: 8 hrs.
> feat: Parse TOC

- src/lib/types/googleConversion.ts
- src/lib/utils/index.ts
- src/routes/api/google-conversion/+server.ts
Resolve #508 
ETA:
Expected time to finish: 3 hr
Time taken so far: 2 hrs
> feat: Problem 508 GDoc Parser Refactor - Paragraph

- src/lib/components/BodyParser/blocks.ts
- src/lib/components/BodyParser/index.ts
resolves #108 
ETA: 4 hrs
Time taken so far: 5 hrs
> feat: Replace the current TOC implementation with the element from the payload

- src/routes/(pages)/+layout.svelte
- src/routes/(pages)/layout.pug
resolves https://github.com/zolotokrylin/holdex.io/issues/2349
estimation: 30min
> fix: full scrollbar area for navbar

- src/lib/components/BodyRenderer/Blocks/table.pug
- src/lib/components/BodyRenderer/Blocks/table.svelte
- src/routes/(pages)/layout.scss
> fix: edge case of table with two cols

- src/lib/components/BodyParser/blocks.ts
- src/lib/components/BodyParser/index.ts
- src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
- src/routes/(pages)/c/mixins.pug
- tailwind.config.cjs
I Implemented new article hero section 
time spent: 7 hours
resolves #526
> feat(ui): redesign Article hero

- src/lib/components/BodyParser/blocks.ts
- src/lib/components/BodyParser/utils.ts
- src/lib/components/BodyRenderer/Blocks/gist.svelte
- src/lib/components/BodyRenderer/item.pug
- src/lib/components/BodyRenderer/item.svelte
- src/lib/types/googleConversion.ts
resolves holdex/marketing#17
Time spent: 8 hours
> feat: embed github gist code snippets into articles

- src/lib/components/Button/style.sass
- src/lib/styles/variables.scss
- tailwind.config.cjs
resolves #544
[Figma Design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=256%3A189&mode=design&t=9sjEXaj72N2e0o6O-1)
Time spent: 1.5 hours
> fix: match button components with figma design

- src/lib/components/BodyRenderer/Blocks/gist.svelte
resolves Holdex/marketing#17
Time spent: 30 minutes
> feat: implement instant gist color theme switch on theme toggle

- src/lib/components/Button/style.sass
> fix(ui): match button component height with design

- src/routes/api/google-conversion/+server.ts
> fix: fixed to display testimonial's avatar on prod environment

- src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
Resolves #571
Spent Time: 1 hours.
> feat: updated jobs category tags and OG tags

- README.md
- src/lib/components/MetaTags/index.svelte
- src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
resolves https://github.com/holdex/holdex-venture-studio/issues/578
> fix: view OG image for articles in companies category

- src/lib/components/Feed/ResourceItem/template.pug
- src/routes/(pages)/c/guides/template.pug
> feat(style): modify job and guide article heading

- DESIGN.md
resolves https://github.com/holdex/marketing/issues/57
[Figma](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=7017%3A51989&mode=design&t=t0tAdHirdZn2fo9l-1)
> docs(ui): view cards on top of Guides page

- src/lib/components/Portfolio/index.svelte
- src/lib/components/Portfolio/template.pug
- src/routes/(pages)/c/mixins.pug
- tailwind.config.cjs
resolves https://github.com/holdex/marketing/issues/61
Test: https://holdex-venture-studio-hhvnemc0j-holdex-accelerator.vercel.app/portfolio
> feat(ui): view continuous rolling strip of investors in Portfolio

- src/lib/components/Portfolio/index.svelte
- src/lib/components/Portfolio/template.pug
- src/routes/(pages)/c/mixins.pug
- src/routes/(pages)/portfolio/template.pug
resolves https://github.com/holdex/marketing/issues/63
Test: https://holdex-venture-studio-83h0f35ez-holdex-accelerator.vercel.app/portfolio
> feat: view Truflation market cap in portfolio page

- src/lib/components/Portfolio/template.pug
- src/routes/(pages)/portfolio/template.pug
resolves https://github.com/holdex/marketing/issues/64
Test: https://holdex-venture-studio-6nccs09ta-holdex-accelerator.vercel.app/portfolio
number gotten from https://www.coingecko.com/en/coins/zebec-protocol
> feat: view zebec market cap in portfolio

- src/lib/components/CompanyLogoStrip/template.pug
- src/routes/(pages)/portfolio/template.pug
test: https://holdex-venture-studio-git-chore-view-45e9e7-holdex-accelerator.vercel.app/portfolio
@angelicawill
> feat: view Hex Trust portfolio in More Projects section

- package.json
- src/lib/components/BodyParser/utils.ts
- src/lib/components/BodyRenderer/Blocks/link.svelte
- src/lib/components/BodyRenderer/Blocks/linkBlock.svelte
- src/lib/components/BodyRenderer/item.pug
- src/lib/components/BodyRenderer/item.svelte
- src/lib/components/Feed/ResourceItem/index.svelte
- src/lib/components/Feed/ResourceItem/template.pug
- src/lib/components/Portfolio/template.pug
- src/lib/utils/index.ts
- src/routes/(pages)/+page.svelte
- src/routes/(pages)/index-mixins.pug
- src/routes/(pages)/layout.pug
- src/routes/api/og/+server.ts
resolves: https://github.com/holdex/marketing/issues/136
> chore: sync environments
